CREATE TABLE "ATG_WIP_Oper_Label"(
 "Trmnl" CHAR(3) NOT NULL ,
 "Job" CHAR(6) NOT NULL ,
 "Suffix" CHAR(3) NOT NULL ,
 "Cur_Seq" CHAR(6) NOT NULL ,
 "Cur_Part" CHAR(20),
 "Cur_Descr" CHAR(30),
 "Qty" NUMERIC(12,4),
 "Qty_Completed" NUMERIC(12,4),
 "Workcenter" CHAR(30),
 "Employee" CHAR(30),
 "Quality_No" CHAR(7),
 "Scrap_Qty" NUMERIC(10,2),
 "Close_Flag" CHAR(1),
 "Part" CHAR(20),
 "Part_Descr" CHAR(30),
 "Customer" CHAR(6),
 "Name" CHAR(50),
 "Next_Seq" CHAR(6),
 "Next_Part" CHAR(20),
 "Next_Descr" CHAR(30),
 "Next_Seq_Start" Date,
 "Next_Seq_Due" Date,
 "WO_Qty" NUMERIC(12,4),
 "WO_Customer_Qty" NUMERIC(12,4),
 "WO_Due_Date" Date,
 "WO_Priority"CHAR(3),
 "LMO" CHAR(1),
 "SCRAP_CODE" CHAR(4),
 "SCRAP_CODE_DESC" CHAR(50),
 "TOP_Parent_Part" CHAR(20), 
 "TOP_Parent_Job" CHAR(6), 
 "TOP_Parent_Suffix" CHAR(3),
 "TOP_Parent_Descr" CHAR(30),
 "Parent_Part" CHAR(20),
 "Parent_Descr" CHAR(30),
 "Parent_Job" CHAR(6),
 "Parent_Suffix" CHAR(3),
 "Parent_InitWC" CHAR(30),
 "Comments" CHAR(350));
